### ISSUE TITLE
koken & PHP

### ISSUE THREAD

**Issue by git-me-if-U-can** [mbolli/koken_php74_patch#2]
hi michel,

i think, that you've got the solution for the current PHP problem, but i have no idea, what you're talking about ... i'm not at all any kind of coder and i didn't even understand your explanations to Tony on march 26. 2021 ...

my provider wants me to upgrade from PHP7.4 to PHP8.0 (or 8.2); he gave me the oportunity to try this out, so i did. my koken-site www.wiese-wiese.de didn't work anymore, so i used the possibility to undo the upgrade.

will your patch help in my case & could you explain, how to use your fix?

Marc from germany

PS: sorry for
1. my bad english
2. my stupidity

**Comment by mbolli** [comment]
Hey @git-me-if-U-can 

Regarding applying the patch, I basically said everything in #1. To manually apply the patch (if you have lots of time), you need to open the patch file with a text editor and then work from top to bottom. Open every file that's mentioned (e.g. via FTP) and apply the changes. And make a backup before starting.

I'm not yet sure about PHP 8 support though, I will have to try it out.

Michael

**Comment by mbolli** [comment]
Just a note, PHP 8 seems to work okayish with the newest version of the patch.

**Comment by git-me-if-U-can** [comment]
thanks a lot, i'll try it.

Marc
